# Generated by Django 6.0.7 on 2026-07-21 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_listings', models.PositiveIntegerField(default=10, help_text='Maximum total listings allowed. Set to 0 for unlimited.')),
                ('max_boosted', models.PositiveIntegerField(default=0, help_text='Maximum boosted listings allowed.')),
                ('max_featured', models.PositiveIntegerField(default=0, help_text='Maximum featured listings allowed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profiles', to='profiles.plan'),
        ),
    ]
