# Generated by Django 6.0.7 on 2026-07-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_plan_agentprofile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
