# Generated by Django 6.0.7 on 2026-07-23 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_report'),
        ('profiles', '0003_agentprofile_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('price', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature bullet points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('next_renewal', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('due', 'Due'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='profiles.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_due', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('due', 'Due'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_features', to='profiles.featuredplan')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_placements', to='agents.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
