# Generated by Django 6.0.7 on 2026-09-03 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_agentprofile_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='unverified', max_length=20)),
                ('nin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nin_verified', models.BooleanField(default=False)),
                ('nin_data', models.JSONField(blank=True, default=dict)),
                ('cac_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cac_company_type', models.CharField(blank=True, max_length=20, null=True)),
                ('cac_verified', models.BooleanField(default=False)),
                ('cac_data', models.JSONField(blank=True, default=dict)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='profiles.agentprofile')),
            ],
            options={
                'verbose_name': 'Agent KYC',
                'verbose_name_plural': 'Agent KYCs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
