# Generated by Django 5.0.14 on 2026-09-14 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_tag_listing_city_listing_country_listing_state_and_more'),
        ('profiles', '0006_agentkyc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField(default=7, help_text='Duration of the boost in days (e.g., 3, 7, 14, 30).')),
                ('price', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature bullet points.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['duration_days', 'price'],
            },
        ),
        migrations.AlterModelOptions(
            name='featuredplan',
            options={'ordering': ['duration_days', 'price']},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_listings',
        ),
        migrations.AddField(
            model_name='agentsubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentsubscription',
            name='payment_method',
            field=models.CharField(default='card', max_length=50),
        ),
        migrations.AddField(
            model_name='agentsubscription',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='featuredplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of marketing feature bullet points.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_verified_badge',
            field=models.BooleanField(default=False, help_text='Displays priority verified agent badge.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_virtual_tour',
            field=models.BooleanField(default=False, help_text='Allows 3D virtual tours and video walkthrough attachments.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_images_per_listing',
            field=models.PositiveIntegerField(default=10, help_text='Maximum property photos allowed per listing (0 for unlimited).'),
        ),
        migrations.AddField(
            model_name='plan',
            name='support_tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('priority', 'Priority'), ('dedicated', 'Dedicated 24/7')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_boosted',
            field=models.PositiveIntegerField(default=2, help_text='Maximum concurrent active pay-as-you-go boosted listings allowed (0 for unlimited).'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_featured',
            field=models.PositiveIntegerField(default=0, help_text='Monthly featured listings allowance bundled into plan (0 for none/unlimited).'),
        ),
        migrations.CreateModel(
            name='ListingBoostPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_expires', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_placements', to=settings.AUTH_USER_MODEL)),
                ('boost_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='profiles.boostplan')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_placements', to='agents.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
