# Generated by Django 5.0.14 on 2026-09-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_boostplan_alter_featuredplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='has_virtual_tour',
        ),
    ]
