# Generated by Django 5.0.14 on 2026-09-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_plan_has_virtual_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='support_tier',
        ),
    ]
