# Generated by Django 6.0.7 on 2026-07-21 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('lodge', 'Lodge'), ('mall', 'Mall'), ('hotel', 'Hotel'), ('villa', 'Villa'), ('condo', 'Condo'), ('shop', 'Shop'), ('land', 'Land'), ('bungalow', 'Bungalow'), ('plaza', 'Plaza'), ('duplex', 'Duplex'), ('multi_story_building', 'Multi-story Building'), ('single_flat', 'Single flat'), ('airbnb', 'Airbnb')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('balconies', models.PositiveIntegerField(default=0)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('facilities', models.JSONField(blank=True, default=list, help_text="List of environment/facilities tags e.g. ['Parking lot', 'Garden']")),
                ('is_published', models.BooleanField(default=True)),
                ('is_boosted', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='listings/')),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.listing')),
            ],
        ),
    ]
