# Generated by Django 6.0.7 on 2026-07-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('sold', 'Sold'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
    ]
