# Generated by Django 6.0.7 on 2026-08-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_listingimage_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of views on this listing.'),
        ),
    ]
