# Generated by Django 6.0.7 on 2026-08-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
