services:
  db:
    image: postgres:15-alpine
    container_name: realestate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=realestate_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: realestate_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=realestate_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=django-insecure--1j@enwddh^0a=r-ix(ihwd1e+e=($=d*p3zk&v7xc=%a-nz6j
      - DEBUG=True
      - ALLOWED_HOSTS=*
    depends_on:
      - db

volumes:
  postgres_data:
