# Generated by Django 6.0.7 on 2026-07-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_suspended_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('agent', 'Agent'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='buyer', max_length=15),
        ),
    ]
